SELECT SUBSTRING(SALES_DATE,1,4) AS YEAR, SUBSTRING(SALES_DATE,6,2) AS MONTH, GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM ONLINE_SALE AS S 
JOIN USER_INFO AS U ON GENDER IS NOT NULL AND U.USER_ID = S.USER_ID
GROUP BY YEAR, MONTH, GENDER HAVING USERS > 0
ORDER BY YEAR, MONTH, GENDER

--- YEAR, MONTH 함수가 따로 있네..
SELECT YEAR(B.SALES_DATE) YEAR, MONTH(B.SALES_DATE) MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) USERS
FROM USER_INFO A INNER JOIN ONLINE_SALE B 
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY 1,2,3;
