WITH FRONT AS (
    SELECT SUM(CODE) AS CODES
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),GRADE AS
(
    SELECT CASE
        WHEN (FRONT.CODES & D.SKILL_CODE AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python'))  THEN 'A'
        WHEN D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN FRONT.CODES & D.SKILL_CODE THEN 'C'
        ELSE NULL
        END AS C, D.ID AS ID
    FROM FRONT, DEVELOPERS  AS D
)

select GRADE.C AS GRADE, D.ID, EMAIL
FROM GRADE
JOIN DEVELOPERS AS D ON D.ID = GRADE.ID
WHERE GRADE.C IS NOT NULL
ORDER BY GRADE.C ,ID
