SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY, SUM(S.SALES * B.PRICE) AS SALES
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID AND SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

-- SUM(S.SALES) * B.PRICE -> SUM(S.SALES * B.PRICE) 
-- 앞에 걸로 풀어서 오랫동안 고민했음,, 카테고리 저자 가 같아도 책 종류가 다르고, 그러면 가격도 달라서 뒤에 걸로 해야돼
