-- 내 풀이 서브쿼리

SELECT U.USER_ID, U.NICKNAME, SP.TOTAL_SALES
FROM USED_GOODS_USER AS U 
JOIN (SELECT WRITER_ID,SUM(PRICE) AS TOTAL_SALES
      FROM USED_GOODS_BOARD 
      WHERE STATUS = 'DONE'
      GROUP BY WRITER_ID HAVING TOTAL_SALES >= 700000
     ) AS SP ON SP.WRITER_ID = U.USER_ID
ORDER BY SP.TOTAL_SALES

-- 서브쿼리 안쓰고 이게 더 나은듯
SELECT USER_ID, NICKNAME, sum(PRICE)TOTAL_SALES
FROM USED_GOODS_BOARD as b, USED_GOODS_USER as u
WHERE b.WRITER_ID = u.USER_ID
and STATUS = 'DONE'
group by 1
having TOTAL_SALES >= 700000
order by 3
