SELECT M.MEMBER_NAME,R.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN (SELECT MEMBER_ID
    FROM MEMBER_PROFILE AS M
    JOIN REST_REVIEW AS R USING(MEMBER_ID)
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1) AS TOP USING(MEMBER_ID)
JOIN MEMBER_PROFILE AS M USING(MEMBER_ID)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT
