-- 내 풀이
SELECT ID, CASE
    WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
    WHEN SIZE_OF_COLONY > 100  AND SIZE_OF_COLONY <=1000 THEN 'MEDIUM'
    ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA
ORDER BY ID

-- BETWEEN 사용한 풀이법
SELECT ID
     , CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
            WHEN SIZE_OF_COLONY BETWEEN 100 AND 1000 THEN 'MEDIUM' 
            ELSE 'HIGH' 
            END AS SIZE
    FROM ECOLI_DATA
    ORDER BY ID
