-- 내 풀이
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME 
FROM DEVELOPERS AS D, SKILLCODES AS S
WHERE (S.NAME = 'Python' OR S.NAME = 'C#')
AND D.SKILL_CODE & S.CODE
ORDER BY D.ID

-- EXISTS 사용한 남의 풀이

SELECT D.ID, D.EMAIL, D.FIRSTNAME, D.LASTNAME
FROM DEVELOPERS D
WHERE EXISTS (
  SELECT 1
  FROM SKILLCODES S
  WHERE (S.CODE & D.SKILL_CODE != 0)
  AND ((S.NAME = 'Python') OR (S.NAME = 'C#'))
  )
ORDER BY D.ID ASC;
