SELECT I.ID, N.FISH_NAME, MT.ML AS LENGTH
FROM FISH_NAME_INFO AS N
JOIN FISH_INFO AS I
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS ML
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS MT ON MT.FISH_TYPE  = N.FISH_TYPE
WHERE I.FISH_TYPE = MT.FISH_TYPE AND I.LENGTH = MT.ML
ORDER BY I.ID

--- 이런 문제는 WITH 사용할 필요성이 있을듯

WITH F AS (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH 
FROM FISH_INFO 
GROUP BY FISH_TYPE),

FF AS (SELECT A.ID,A.FISH_TYPE,F.LENGTH 
FROM FISH_INFO A LEFT JOIN F USING(FISH_TYPE) 
WHERE F.LENGTH=A.LENGTH AND F.FISH_TYPE=A.FISH_TYPE)

SELECT FF.ID, B.FISH_NAME, FF.LENGTH
FROM FF LEFT JOIN FISH_NAME_INFO B USING(FISH_TYPE)
ORDER BY 1
