WITH CTE AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXSIZE
FROM ECOLI_DATA
GROUP BY YEAR
)

SELECT C.YEAR, (C.MAXSIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS E
LEFT JOIN CTE AS C ON YEAR(E.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY C.YEAR, YEAR_DEV
