SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
LEFT JOIN (
    SELECT I.ITEM_ID AS ID, COUNT(T.PARENT_ITEM_ID) AS CHD_CNT
    FROM ITEM_INFO AS I 
    LEFT JOIN ITEM_TREE AS T ON T.PARENT_ITEM_ID = I.ITEM_ID
    GROUP BY I.ITEM_ID
) AS C ON C.ID = I.ITEM_ID
WHERE C.CHD_CNT = 0
ORDER BY I.ITEM_ID DESC

-- IN, EXISTS 사용한 풀이
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO F
WHERE F.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY 1 DESC

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INFO
WHERE NOT EXISTS (SELECT 1  FROM ITEM_TREE TREE WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY ITEM_ID DESC
